---
# tasks file for ansible-role-awx-letsencrypt
- name: "Install and Setup Dependencies"
  import_tasks: setup.yml

- name: "Generate Certificates"
  import_tasks: certificate.yml

- name: "Configure AXW with new Certificate"
  import_tasks: awx.yml
